# Common sections
defaults: &defaults
  working_directory: ~/aur
  docker:
    - image: imrehg/archlinux-makepkg


updatepackage: &updatepackage
  name: Update packages
  command: sudo pacman -Syu --noconfirm

gitupdate: &gitupdate
  name: Git repo updates
  command: |
    sed -i "s#ssh://aur@aur.archlinux.org#https://aur.archlinux.org#" .gitmodules
    git submodule update --init

pkgbuildtest: &pkgbuildtest
  name: Testing PKGBUILD
  command: |
    cd ~/aur/${CIRCLE_JOB}
    namcap PKGBUILD

buildtest: &buildtest
  name: Building package
  command: |
    cd ~/aur/${CIRCLE_JOB}
    sudo pacman -S python-setuptools
    yaourt --m-arg --skipchecksums --m-arg --skippgpcheck -S --needed $(source PKGBUILD && printf '%s ' "${depends[@]}") --noconfirm
    yaourt --m-arg --skipchecksums --m-arg --skippgpcheck -S --needed $(source PKGBUILD && printf '%s ' "${makedepends[@]}") --noconfirm
    makepkg --noconfirm

# Main
version: 2
jobs:
  seastar-git:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - seastar*gz
  wavm-git:
    <<: *defaults
    steps:
      - run:
          <<: *updatepackage
      - checkout
      - run:
          <<: *gitupdate
      - run:
          <<: *pkgbuildtest
      - run:
          <<: *buildtest
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - wavm*gz
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_BUILD_NUM} /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts


workflows:
  version: 2
  build:
    jobs:
      - seastar-git
      - wavm-git
      - deploy:
          requires:
            - seastar-git
            - wavm-git
